# Generated by Django 5.0.1 on 2024-04-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="signature",
            field=models.CharField(
                default="Makeel: Don't cry becuase it is over,Smile because it happened",
                max_length=140,
            ),
        ),
    ]
